import './icons.pcss';
export { default as LoupIcon } from './loup';
export { default as PaperClipIcon } from './paper-clip';
export { default as ArrowIcon } from './arrow';
export { default as CheckmarkIcon } from './checkmark';
export { default as ImageIcon } from './image';
export { default as PlusIcon } from './plus';
export { default as FileIcon } from './file';
export { default as LocationIcon } from './location';
export { default as LoaderIcon } from './loader';
